packages:
  - 'apps/*'
  - 'packages/*'
  - 'shared/*'
# pnpm version 11+
# pnpm:
#   overrides:
#     '@wangeditor-next/editor-for-vue>@wangeditor-next/editor': 'workspace:*'
  # # 另外，确保peerDependencies不会导致多个实例
  # strict-peer-dependencies: false
  # auto-install-peers: true